### ISSUE TITLE
Tasks and status bar assume dark color theme

### ISSUE THREAD

**Issue by mjgardner** [seita1996/vscode-gitlab-task-list#20]
The sidebar task list displays dark cards despite using a light color theme, and the status bar indicator displays yellow when there are open tasks, which is barely visible on a light theme’s background.

<img width="1068" alt="image" src="https://github.com/seita1996/vscode-gitlab-task-list/assets/133483/61652cab-7143-46c2-b6d4-acad52c57759">

**Comment by seita1996** [comment]
@mjgardner 

Oh my god.
Thanks for the report!
I'll fix it.

**Comment by seita1996** [comment]
Light Theme

![image](https://github.com/seita1996/vscode-gitlab-task-list/assets/19267892/1c0ff9da-0025-4872-b053-0e42511d18c0)

Dark Theme

![image](https://github.com/seita1996/vscode-gitlab-task-list/assets/19267892/c32e4fd3-0288-4712-a8d1-3c145863e477)

**Comment by seita1996** [comment]
@mjgardner 

The fixes have been completed and a new version has been released.
Update your VSCode extension and check it out.
